/* radare2 - BSD - Copyright 2025-2026 - pancake */

#include <hbc/hbc.h>
#include <ctype.h>

static void sanitize_identifier(const char *src, char *dst, size_t dst_size) {
	size_t out = 0;
	for (size_t j = 0; src[j] && out + 1 < dst_size; j++) {
		char c = src[j];
		dst[out++] = (isalnum ((unsigned char)c) || c == '_')? c: '_';
	}
	dst[out] = '\0';
}

static void string_flag_name(const char *str, u32 index, char *dst, size_t dst_size) {
	char preview[64] = { 0 };
	size_t out = 0;
	if (str) {
		for (size_t i = 0; str[i] && i < 32 && out + 1 < sizeof (preview); i++) {
			unsigned char c = (unsigned char)str[i];
			preview[out++] = (c >= 32 && c < 127)? (char)c: '_';
		}
	}
	preview[out] = '\0';

	char sanitized[64] = { 0 };
	sanitize_identifier (preview, sanitized, sizeof (sanitized));
	snprintf (dst, dst_size, "%s_%u", sanitized[0]? sanitized: "str", index);
}

Result _hbc_generate_r2_script(const char *input_file, const char *output_file) {
	if (!input_file) {
		return ERROR_RESULT (RESULT_ERROR_INVALID_ARGUMENT, "Input file is NULL");
	}

	HBC *hbc = NULL;
	Result result = hbc_open (input_file, &hbc);
	if (result.code != RESULT_SUCCESS) {
		fprintf (stderr, "Error reading file: %s\n", result.error_message);
		return result;
	}

	FILE *out = stdout;
	if (output_file) {
		out = fopen (output_file, "w");
		if (!out) {
			hbc_close (hbc);
			fprintf (stderr, "Error opening output file: %s\n", output_file);
			return ERROR_RESULT (RESULT_ERROR_FILE_NOT_FOUND, "Failed to open output file");
		}
	}

	HBCHeader header = { 0 };
	result = hbc_get_header (hbc, &header);
	if (result.code != RESULT_SUCCESS) {
		if (output_file) {
			fclose (out);
		}
		hbc_close (hbc);
		return result;
	}

	fprintf (out, "# R2 script for Hermes bytecode file: %s\n", input_file);
	fprintf (out, "# Generated by r2hermes\n\n");
	fprintf (out, "# Hermes File Version: %u\n", header.version);
	fprintf (out, "# File Size: %u bytes\n", header.fileLength);
	fprintf (out, "# Function Count: %u\n\n", header.functionCount);
	fprintf (out, "# Basic file structure flags\n");
	fprintf (out, "f hbc.header=0x0\n");
	fprintf (out, "f hbc.header.size=0x%lx\n", (unsigned long)sizeof (HBCHeader));

	const u32 function_count = R_MIN (hbc_function_count (hbc), 50000);
	fprintf (out, "\n# Function flags\n");
	for (u32 i = 0; i < function_count; i++) {
		HBCFunc func = { 0 };
		if (hbc_get_function_info (hbc, i, &func).code != RESULT_SUCCESS) {
			continue;
		}
		char name[64];
		snprintf (name, sizeof (name), "func_%u", i);
		if (func.size > 0) {
			fprintf (out, "'f func.hermes.%s 0x%x 0x%x\n", name, func.size, func.offset);
		} else {
			fprintf (out, "'f func.hermes.%s=0x%x\n", name, func.offset);
		}
	}
	fprintf (out, "# Successfully read %u function headers\n\n", function_count);

	fprintf (out, "# String flags\n");
	const u32 string_count = R_MIN (hbc_string_count (hbc), 100000);
	u32 successful_strings = 0;
	for (u32 i = 0; i < string_count; i++) {
		HBCStringMeta meta = { 0 };
		if (hbc_get_string_meta (hbc, i, &meta).code != RESULT_SUCCESS) {
			continue;
		}
		const char *str = NULL;
		(void)hbc_get_string (hbc, i, &str);

		char name[96];
		string_flag_name (str, i, name, sizeof (name));
		const u32 bpc = meta.isUTF16? 2: 1;
		fprintf (out, "'f str.%s %u 0x%08x\n", name, meta.length * bpc, meta.offset);
		successful_strings++;
	}
	fprintf (out, "# Generated %u string flags\n", successful_strings);

	if (output_file) {
		fclose (out);
		printf ("\n[+] R2 script output wrote to \"%s\"\n\n", output_file);
	}
	hbc_close (hbc);
	return SUCCESS_RESULT ();
}
