name: Meson Build

on:
  push:
  workflow_dispatch: {}

jobs:
  build:
    name: Build with meson and r2 plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install build deps
        run: sudo apt-get update -y && sudo apt-get install -y build-essential meson ninja-build pkg-config

      - name: Install radare2
        id: r2
        uses: radareorg/github-actions@v1

      - name: Build library and r2 plugin with meson
        run: meson setup builddir && meson compile -C builddir
