name: Windows Build

on:
  push:
  workflow_dispatch: {}

jobs:
  build-windows:
    name: Build for Windows with MSVC
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12.x

      - name: Prepare MSVC toolchain
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install dependencies
        shell: bash
        run: |
          pip install meson ninja

      - name: Install radare2
        id: r2
        uses: radareorg/github-actions@v1

      - name: Build with Meson
        shell: cmd
        run: |
          meson setup builddir -Dprefix=%cd%\install
          meson compile -C builddir
          meson install -C builddir

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-windows
          path: builddir\install\**\*
